image: Visual Studio 2015
test: off
deploy: off
clone_folder: C:\TBuild\tdesktop
environment:
  GYP_MSVS_OVERRIDE_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2015\Community\'
  GYP_MSVS_VERSION: 2015
  matrix:
   - BUILD_VERSION:
  API_ID:
    secure: 2YbTu9xNNPeYl6IUAhCS6A==
  API_HASH:
    secure: 88rlDnhzZhcStAhXGkc3pdM3whMbAmvqbhhrqkTr3P/B9jVFy0NwvtpvjNkSiW1r
matrix:
  fast_finish: true

before_build:
  - .\.appveyor\install.bat

build:
  project: Telegram\Telegram.sln

configuration:
  - Release

artifacts:
  - path: out\Release\Telegram.exe
    name: Telegram_release.exe
  - path: out\Release\Telegram.exe.pdb
    name: Telegram_release.exe.pdb
