image: Visual Studio 2019
test: off
deploy: off
clone_folder: C:\TBuild\tdesktop-{build}
environment:
  GYP_MSVS_OVERRIDE_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\'
  GYP_MSVS_VERSION: 2019
  matrix:
   - BUILD_VERSION:

matrix:
  fast_finish: true

before_build:
  - .\.appveyor\install.bat

build:
  project: Telegram\Telegram.sln

artifacts:
  - path: out\Debug\Telegram.exe
    name: Telegram_debug.exe
  - path: out\Debug\Telegram.exe.pdb
    name: Telegram_debug.exe.pdb
